# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CICD

on:
  push:
    branches: [ deploy ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout SourceCode
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build Project
      run: mvn clean package -DskipTests
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker Image
      run: docker build -t ankitfs/crudapplication .
    - name: Publish Image to Docker Hub
      run: docker push ankitfs/crudapplication:latest

  deploy:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: Pull Image from DockerHub
        run: docker pull ankitfs/crudapplication:latest
      - name: Delete Old Container
        run: docker rm -f springboot-crud-application
      - name: Run docker container
        run: docker -d -p 8080:8080 --name springboot-crud-application ankitfs/crudapplication
